#!/bin/bash

rm -f support.js

if [ -f $1-platform.js ]
    then
	echo 'Adding file' $1'-support.js';
	cat $1-platform.js >> support.js;
    else
	echo "Requires platform either browser or node"
	exit
fi

for i in `cat order`; do
	echo 'Adding file' $i;
	cat $i >> support.js;
done;

echo 'Adding exports for testing'
cat exports.js >> support.js;
