#!/bin/bash

origdir=`pwd`
cd `dirname $0`

if [ $2 ]
    then
	target=$origdir/$2
    else
	target=test-support.js
fi

rm -f $target

if [ -f $1-platform.js ]
    then
	echo 'Adding file' $1'-platform.js';
	cat $1-platform.js >> $target;
    else
	echo "Requires platform either browser or node"
	exit
fi

for i in `cat order`; do
	echo 'Adding file' $i;
	cat $i >> $target;
done;

echo 'Adding exports for testing'
cat exports.js >> $target;
