#!/bin/bash

origdir=`pwd`
cd `dirname $0`

if [ $2 ]
    then
	target=$origdir/$2
    else
	target=test-support.js
fi

rm -f $target

if [ -f $1-platform.js ]
    then
	echo 'Adding platform-specific code';
	cat $1-platform.js >> $target;
    else
	echo "Requires platform either browser or node"
	exit
fi

echo 'Concatinating main source files';
for i in `cat order`; do
	echo '    adding' $i;
	cat $i >> $target;
done;

echo 'Adding exports for testing'
cat exports.js >> $target;


echo
echo 'Done building'
